#!/bin/sh

# /vagrant/vagrant/ubuntu16/scripts/apache-install.sh
# /vagrant/vagrant/ubuntu16/scripts/composer-install.sh
# /vagrant/vagrant/ubuntu16/scripts/java-openjdk-v10-install.sh
# /vagrant/vagrant/ubuntu16/scripts/java-openjdk-v11-install.sh
# /vagrant/vagrant/ubuntu16/scripts/java-openjdk-v8-install.sh
# /vagrant/vagrant/ubuntu16/scripts/java-openjdk-v9-install.sh
# /vagrant/vagrant/ubuntu16/scripts/java-oracle-jdk-install.sh
# /vagrant/vagrant/ubuntu16/scripts/laravel-install.sh
# /vagrant/vagrant/ubuntu16/scripts/maven-install.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v3.4-install-config.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v3.4-install.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v3.6-install-config.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v3.6-install.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v4.0-install-config.sh
# /vagrant/vagrant/ubuntu16/scripts/mongodb-server-v4.0-install.sh
# /vagrant/vagrant/ubuntu16/scripts/mysql-server-v5.7-install-config.sh
# /vagrant/vagrant/ubuntu16/scripts/mysql-server-v5.7-install-silent.sh
# /vagrant/vagrant/ubuntu16/scripts/mysql-server-v5.7-install.sh
# /vagrant/vagrant/ubuntu16/scripts/mysql-server-v5.7-prepare-db-with-password.sh
# /vagrant/vagrant/ubuntu16/scripts/mysql-server-v5.7-prepare-db.sh
# /vagrant/vagrant/ubuntu16/scripts/nginx-install.sh
# /vagrant/vagrant/ubuntu16/scripts/nodejs-pm2-install.sh
# /vagrant/vagrant/ubuntu16/scripts/nodejs-v10-install.sh
# /vagrant/vagrant/ubuntu16/scripts/nodejs-v11-install.sh
# /vagrant/vagrant/ubuntu16/scripts/nodejs-v6-install.sh
# /vagrant/vagrant/ubuntu16/scripts/nodejs-v8-install.sh
# /vagrant/vagrant/ubuntu16/scripts/php-v7.2-install.sh
# /vagrant/vagrant/ubuntu16/scripts/postgresql-server-v9.5-install-config.sh
# /vagrant/vagrant/ubuntu16/scripts/postgresql-server-v9.5-install.sh
# /vagrant/vagrant/ubuntu16/scripts/postgresql-server-v9.5-prepare-db.sh
# /vagrant/vagrant/ubuntu16/scripts/sqlite-server-v3-install.sh
# /vagrant/vagrant/ubuntu16/scripts/ssh-backup.sh
# /vagrant/vagrant/ubuntu16/scripts/ssh-restore.sh
# /vagrant/vagrant/ubuntu16/scripts/symfony-install.sh
# /vagrant/vagrant/ubuntu16/scripts/tomcat-install.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-install-from-url.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-v12-install.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-v13-install.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-v14-install.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-v15-install.sh
# /vagrant/vagrant/ubuntu16/scripts/wildfly-v16-install.sh
